/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property message
 */
@JsonClass(generateAdapter = true)
data class BasicServerResponseServerMessage(
    @Json(name = "message") @field:Json(name = "message") var message: String? = null
)
