/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property email
 * @property fullName
 * @property phoneNumber
 * @property profilePicture
 */
@JsonClass(generateAdapter = true)
data class ListedUser(
    @Json(name = "email") @field:Json(name = "email") var email: String? = null,
    @Json(name = "full name") @field:Json(name = "full name") var fullName: String? = null,
    @Json(name = "phone number") @field:Json(name = "phone number") var phoneNumber: String? = null,
    @Json(name = "profile picture") @field:Json(name = "profile_picture") var profilePicture: String? = null
)
