/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Swagger Petstore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property category
 * @property name
 * @property photoUrls
 * @property tags
 * @property status pet status in the store
 */
@JsonClass(generateAdapter = true)
data class Pet(
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "photoUrls") @field:Json(name = "photoUrls") var photoUrls: List<String>,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "category") @field:Json(name = "category") var category: Category? = null,
    @Json(name = "tags") @field:Json(name = "tags") var tags: List<Tag>? = null,
    @Json(name = "status") @field:Json(name = "status") var status: Pet.StatusEnum? = null
) {
    /**
     * pet status in the store
     * Values: AVAILABLE, PENDING, SOLD
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "available") AVAILABLE("available"),
        @Json(name = "pending") PENDING("pending"),
        @Json(name = "sold") SOLD("sold")
    }
}
