/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property AppServer
 * @property AuthServer
 * @property MediaServer
 */
@JsonClass(generateAdapter = true)
data class PingResponse(
    @Json(name = "App Server") @field:Json(name = "App Server") var AppServer: String? = null,
    @Json(name = "Auth Server") @field:Json(name = "Auth Server") var AuthServer: String? = null,
    @Json(name = "Media Server") @field:Json(name = "Media Server") var MediaServer: String? = null
)
