/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property DeleteUser
 */
@JsonClass(generateAdapter = true)
data class SuccessfulDeleteUserResponse(
    @Json(name = "Delete user") @field:Json(name = "Delete user") var DeleteUser: String? = null
)
