/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Swagger Petstore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property name
 */
@JsonClass(generateAdapter = true)
data class Tag(
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
