/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Swagger Petstore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property username
 * @property firstName
 * @property lastName
 * @property email
 * @property password
 * @property phone
 * @property userStatus User Status
 */
@JsonClass(generateAdapter = true)
data class User(
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "username") @field:Json(name = "username") var username: String? = null,
    @Json(name = "firstName") @field:Json(name = "firstName") var firstName: String? = null,
    @Json(name = "lastName") @field:Json(name = "lastName") var lastName: String? = null,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null,
    @Json(name = "password") @field:Json(name = "password") var password: String? = null,
    @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null,
    @Json(name = "userStatus") @field:Json(name = "userStatus") var userStatus: Int? = null
)
