/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import android.os.Parcelable
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.android.parcel.Parcelize

/**
 * @property Id
 * @property comments
 * @property dislikes
 * @property isPrivate
 * @property likes
 * @property title
 * @property uploadDate
 * @property url
 * @property user
 */

@Parcelize
@JsonClass(generateAdapter = true)
data class Video(
    @Json(name = "_id") @field:Json(name = "_id") var Id: String? = null,
    @Json(name = "comments") @field:Json(name = "comments") var comments: Comment? = null,
    @Json(name = "dislikes") @field:Json(name = "dislikes") var dislikes: List<String>? = null,
    @Json(name = "is_private") @field:Json(name = "is_private") var isPrivate: Boolean? = null,
    @Json(name = "likes") @field:Json(name = "likes") var likes: List<String>? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "upload_date") @field:Json(name = "upload_date") var uploadDate: String? = null,
    @Json(name = "url") @field:Json(name = "url") var url: String? = null,
    @Json(name = "user") @field:Json(name = "user") var user: String? = null
) : Parcelable
