/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property description
 * @property isPrivate
 * @property title
 * @property url
 * @property user
 */
@JsonClass(generateAdapter = true)
data class VideoToUpload(
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "isPrivate") @field:Json(name = "isPrivate") var isPrivate: Boolean? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "url") @field:Json(name = "url") var url: String? = null,
    @Json(name = "user") @field:Json(name = "user") var user: String? = null
)
