/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: A swagger API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.chotuve_android_client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property Id
 * @property title
 * @property uploadDate
 * @property url
 * @property user
 */
@JsonClass(generateAdapter = true)
data class VideoListInner(
    @Json(name = "_id") @field:Json(name = "_id") var Id: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "upload_date") @field:Json(name = "upload_date") var uploadDate: String? = null,
    @Json(name = "url") @field:Json(name = "url") var url: String? = null,
    @Json(name = "user") @field:Json(name = "user") var user: String? = null
)
